version: "3"

services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/db
    ports:
      - "5435:5432"

  api:
    build: .
    command: python3 easy_teaching_api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
